### ISSUE TITLE
Strange characters in items

### ISSUE THREAD

**Issue by zefir6** [kamaln7/karmabot#28]
I get strange encoding/characters in the names. When it repeats the name first time, it looks normal (though it loses case which is pity), but then it shows garbled chars.
![issue](https://cloud.githubusercontent.com/assets/22873697/26833086/b1e8d134-4ad1-11e7-9715-39af507e8c34.PNG)

**Comment by kamaln7** [comment]
This is actually an intended feature! The first letter of each name is "munged" in order to stop any team members from getting pinged/notified when the leaderboard is printed. I could add a toggle if you do not like that feature though.
