### ISSUE TITLE
Add the ability to change how karmabot replies

### ISSUE THREAD

**Issue by andrewthetechie** [kamaln7/karmabot#50]
It would be great if we could set how karmabot responds. For example, I would prefer karmabot reply to karma requests as a thread, to keep the clutter in a channel down.

In addition, I've had a request to "turn off" the DMs for reaction karma - if we could redirect those messages to a thread that would solve that problem too.

**Comment by kamaln7** [comment]
I like that!

**Comment by kamaln7** [comment]
Released: https://github.com/kamaln7/karmabot/releases/tag/v1.6.0

cc @andrewthetechie
